title: "Arnab Dey | CloudOps/DevOps Engineer"
description: "Dynamic CloudOps/DevOps Engineer with 14 years of IT experience"
url: "https://arnabdey73.github.io"
markdown: kramdown
theme: "minima"
plugins:
  - jekyll-seo-tag
remote_theme: jekyll/minima
author:
  name: "Arnab Dey"
  email: "arnabdey009@gmail.com"
  linkedin: "https://www.linkedin.com/in/arnabdey73"
  github: "https://github.com/arnabdey73"
