const fs = require('fs');
const path = require('path');

// Define categories for CSS files
const cssCategories = {
  layout: [
    'header-footer-fonts.css',
    'site-footer.css',
    'hero-banner.css',
    'intro-card.css',
    'page-title.css',
  ],
  components: [
    'assignment-cards.css',
    'assignment-card-fix.css',
    'blog-feed.css',
    'blog-feed-temp-error.css',
    'blog-note.css',
    'blog-placeholder.css',
    'blog-post-image-fix.css',
    'card-shadows.css',
    'tech-stack.css',
    'tech-stack-mini.css',
  ],
  styles: [
    'typography.css',
    'themes.css',
    'theme-transitions.css',
    'timeline.css',
  ],
  icons: [
    'certification-tech-icons.css',
    'icons-unified.css',
    'mail-icon-fix.css',
    'tech-logos.css',
  ]
};

// Function to concatenate CSS files
function concatenateCssFiles(category, files) {
  console.log(`Processing ${category} files...`);
  let concatenated = `/* Consolidated ${category} styles */\n\n`;
  
  // Add comment to indicate this is an auto-generated file
  concatenated += `/* This file was automatically generated by the CSS consolidation script */\n`;
  concatenated += `/* Last updated: ${new Date().toISOString()} */\n\n`;
  
  files.forEach(file => {
    const filePath = path.join(__dirname, 'assets', 'css', file);
    
    try {
      if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        concatenated += `/* From: ${file} */\n${content}\n\n`;
        console.log(`✓ Added ${file}`);
      } else {
        console.log(`⚠ File not found: ${file}`);
      }
    } catch (error) {
      console.error(`Error processing ${file}:`, error);
    }
  });
  
  return concatenated;
}

// Process each category
Object.entries(cssCategories).forEach(([category, files]) => {
  const output = concatenateCssFiles(category, files);
  const outputPath = path.join(__dirname, 'assets', 'css', `${category}.css`);
  
  fs.writeFileSync(outputPath, output);
  console.log(`✓ Created ${outputPath}`);
});

// Create a consolidated.css that imports all category files
const importStatements = Object.keys(cssCategories)
  .map(category => `@import "${category}.css";`)
  .join('\n');

const consolidatedCss = `/* Consolidated Styles */
/* This file was automatically generated - DO NOT EDIT DIRECTLY */
/* Last updated: ${new Date().toISOString()} */

${importStatements}
`;

fs.writeFileSync(path.join(__dirname, 'assets', 'css', 'consolidated.css'), consolidatedCss);
console.log('✓ Created consolidated.css');

console.log('CSS consolidation complete!');
